### ISSUE TITLE
port-forwarding broken?

### ISSUE THREAD

**Issue by robertmuth** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#30]
I setup port-forwarding using the GUI but it does not seem to work at all.
I have two routers cascaded so I can test this easily.
The inner router forwards a http server from wan:8877 to lan:8877

running wget <wan-ip>:8877 from the outside does not work
running wget <wan-ip>:8877 from inside the inner router does not work
running wget <lan-ip>:8877 from inside the inner router DOES work

**Comment by fernandofig** [comment]
I don't really have a solution to your problem, sorry!

But one question: are you using the release from Dec 8th, or are you using a nightly build? I'm asking because I've been planning on upgrading the current (OpenWRT CC) version on my couple of Archer C7's  at my house to this custom built version. I was planning on going with the release from Dec 8th (if only because the FAQ states it has somewhat better QA), but if it has port-forwarding broken as you say, I'll probably just hold on at least until there's a new release.

If you're on the release version, maybe try the nightly build? Or vice-versa?

Anyway, don't expect any help from the maintainer of this build... I mean, he's doing a good job, but other than pushing builds here, he's apparently not really active on checking issues or reviewing pull requests...

**Comment by robertmuth** [comment]
I tried both the regular and the nightly build and neither worked.
Neither did the older Gargoyle/OpenWRT release I tried afterwards.

At this point I doubting my sanity.
I would be nice if somebody could confirm that port-forwarding is indeed broken
when configured via the GUI.

**Comment by fernandofig** [comment]
FWIW, I can confirm that OpenWRT CC (OpenWrt Chaos Calmer 15.05.1 / LuCI 15.05-149-g0d8bbd2 Release (git-15.363.78009-956be55) has portforwarding working fine on my Archer C7 v2. Maybe try that one?

**Comment by robertmuth** [comment]
The problem, it turns out, was a double NATing issue on my end
